### PR TITLE
Add Manual Storable Instances for DPIXid and VersionInfo (#26)

### PR DESCRIPTION
**Pull request by tusharad**
This PR addresses issue #26 by implementing manual Storable instances for DPIXid and VersionInfo, instead of relying on GStorable. 
I kindly request a review of Implementation (whether it aligned with best practices).

If the approach is deemed correct, I intend to implement manual Storable instances for other types as part of this refactoring effort. Feel free to suggest any changes, optimizations, or best practices that could enhance the implementation. Thank you for your time and guidance!

@apkhandkar @dmjio

### CODE REVIEW

**Comment by dmjio** [comment]
@tusharad adding a test would be helpful

**Comment by tusharad** [comment]
@dmjio 

I considered adding a test case to verify if the `DPIXid` structure supports round-trip poke and peek operations correctly. However, since `DPIXid`, `VersionInfo`, and the `getClientVersion` function are not exposed, I decided against it. Additionally, there are already sufficient transaction tests in place, and the functionality of `DPIXid` is indirectly tested through those.

To ensure everything is working as expected, I ran the `getClientVersion` function, and it executed successfully.

If there's a specific test case you'd like me to include or want to expose and test getClientVersion function, please let me know. Thanks!

**Comment by tusharad** [comment]
@dmjio 

Added round-trip test cases for VersionInfo and DPIXid to ensure their Storable instances are working correctly. For this, I had to expose DPIXid from the Transaction module to make it accessible for testing. Also added Eq instance for DPIXid (Not sure why it was missing previously, but it is necessary for the test assertions). This commit is related to Issue #20, which discusses adding round-trip instance tests. Let me know if anything else required.

Thanks.

**Comment by dmjio** [comment]
LGTM 👍🏼

**Pull request merged**
